### PR TITLE
learning_ros task

### PR DESCRIPTION
**Pull request by cristinayyds**
first pull request

### CODE REVIEW

**Comment by cristinayyds** [comment]
second pull request

**Review by bismarckkk — CHANGES_REQUESTED** [review]
需要按review comment修改，并按lint给出的提示信息进行格式规范（回调的格式会报错且没有良好的规避方案，但其他错误均需要修改

**Review by bismarckkk — APPROVED** [review]
代码没啥问题了，按lint的提示把格式整整好

**Comment by cristinayyds** [comment]
being amending

**Comment by cristinayyds** [comment]
the client_node.cpp still has 2 problems, the server still has 10 problems.As for the requirement of the length <=80 can not be solved with appropriate methods.

**Comment by cristinayyds** [comment]
哦，原来等号后可直接换行。经过修改，尽力了。。。。

**Comment by bismarckkk** [comment]
ok，没啥别的问题了

**Pull request closed without merging**
